### PR TITLE
feat: update Next.js configuration and migrate to Sass module system

### PR DESCRIPTION
**Pull request by lightyfr**
This pull request includes several updates to the configuration and dependencies of the project, as well as changes to the SCSS import syntax. The most important changes involve updating Next.js to the latest and greatest Next.JS 15, modifying the `package.json` dependencies, and changing the SCSS import statements to use the `@use` rule.

### Configuration and Dependencies Updates:
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L15-R29): Updated `next` to latest version `15.0.3`, `react` and `react-dom` to version `19.0.0-rc-66855b96-20241106`, and their respective type definitions to `19.0.0-rc.1`.
* [`next.config.mjs`](diffhunk://#diff-18c049b08c4a0f5ab451c598aeb2c4848bb9d7877b51ca3e5effb94a225814d2R1-R7): Added `sassOptions` to silence deprecations for the legacy JS API.
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L5-R5): Updated the `dev` script to use `next dev --turbopack`, significantly improving dev start times.

### SCSS Import Syntax Changes:
* [`src/once-ui/styles/index.scss`](diffhunk://#diff-dbe240afc7518a9dc16717ec00b52297e4f274ed0b8e67c3115d1e91dad0e0a7L1-R8): Changed all SCSS import statements from `@import` to `@use`.
* [`src/once-ui/tokens/index.scss`](diffhunk://#diff-101b9008ad3430cb95d58e5d53a8d668d8e7deb43e338aa1e8de7bc11ea109f4L1-R7): Changed all SCSS import statements from @import to @use.
* Changed all SCSS import statements from `@import` to `@use`.
* Summary: Upgrades to Latest Next.JS 15 and removes Sass deprecations

### CODE REVIEW

**Comment by lightyfr** [comment]
@lorant-one

**Comment by lorant-one** [comment]
this is beyond amazing @lightyfr! there's a tiny issue caused by floating-ui not being compatible with the react 19 rc, so i need to install the packages with the legacy-peer-deps flag when using npm. this makes me a bit hesitant to merge it right away. i'll need to investigate when they plan to upgrade to the react rc.

**Comment by lightyfr** [comment]
@lorant-one Once floating-ui becomes compatible with react 19 rc, will this get merged?

**Comment by lorant-one** [comment]
yeah of course it will @lightyfr :)

**Pull request closed without merging**
